Style/LambdaCall:
  EnforcedStyle: braces

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

AllCops:
  TargetRubyVersion: 2.5
